development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails-dev
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 5
  timeout: 5000

test:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails-test
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 5
  timeout: 5000

production:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: rails-prod
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 20
  timeout: 5000
